### ISSUE TITLE
File I/O Utility

### ISSUE THREAD

**Issue by WyattRoss** [ezasm-org/rezasm#10]
**As a** Developer
**I want** A robust and functional file input output utility
**So that** I can implement things such as StdIn from file and opening arbitrary code files

**Request Description**
We don't a way of opening and reading from files, please implement one. This needs to work on all platforms. Find a crate or write it yourself, it doesn't matter that much. However, it should have the ability to access the file non-sequentially, that is to say similarly to Java's `RandomAccessFile`

**Comment by michaelni678** [comment]
fixed by https://github.com/ezasm-org/rezasm/pull/30
