### ISSUE TITLE
CLI IO

### ISSUE THREAD

**Issue by TrevorBrunette** [ezasm-org/rezasm#19]
**As a**  Program user
**I want** to be able to load files 
**So that**  I can use the CLI app.

**Request Description**
File I/O with the CLI app is not yet implemented. Implement that.

**Comment by WyattRoss** [comment]
Implementing this requires #10 to be completed already, or requires an implementer to resolve both issues concurrently.

**Comment by michaelni678** [comment]
Closing bc https://github.com/ezasm-org/rezasm/pull/30
