### ISSUE TITLE
Import Instruction

### ISSUE THREAD

**Issue by TrevorBrunette** [ezasm-org/rezasm#56]
**As a** program user
**I want** to be able to use multi-file programs, importing code from other files  
**So that** my code can be split into multiple files.

**Request Description**
Implement an "import" instruction that can import code from other files on the system.  
We need to support both absolute paths and relative paths. We also need the capability to disable relative paths for the web-application.  

`import "/path/to/file.ez"`  
`import "relative/path/to/file.ez"`  

- You can use the existing simulation::Program struct to store data about the files already imported.  
- Running the same import line again should do NOTHING on successive calls.  
- The initial/main file will have a file ID of 0 and will be the entry point.  
- File IDs should increase by 1 with each new code file imported.  
- Importing a file which does not exist should result in a "File Not Found Error" of some sort.  
- Files should be able to be imported on windows using `/`.
- We will need to test this thoroughly on both Windows, Mac, and Linux.

**Comment by TrevorBrunette** [comment]
I might take this issue from you -- have you already started work on it? @michaelni678

**Comment by michaelni678** [comment]
> I might take this issue from you -- have you already started work on it? @michaelni678

https://github.com/ezasm-org/rezasm/compare/import_instr?expand=1
progress so far
