### ISSUE TITLE
[BUG] the $zero register is writable

### ISSUE THREAD

**Issue by WyattRoss** [ezasm-org/rezasm#76]
**Environment (please complete the following information):**
 - OS: Any

**Describe the bug**
`move $zero 10` sets the `$zero` register to 10. It shouldn't.

**Expected behavior**
Should stay at 0

**Comment by WyattRoss** [comment]
Other sets (such as add) also probably cause this to happen. Modifying each instruction individually would **not** be an acceptable solution.

**Comment by TrevorBrunette** [comment]
Another possible solution would be to remove the zero register. I am not sure it is very useful in this language.

**Comment by WyattRoss** [comment]
Either is acceptable, I suppose.
